### ISSUE TITLE
raft: fix Ready.MustSync logic

### ISSUE THREAD

**Issue by siddontang** [tikv/raft-rs#128]
Refer https://github.com/etcd-io/etcd/pull/10106

Seem that we have already used the Raft hard state, not the ready's, but we need to port the test. 

Btw, seem that we don't consider Entries number for MustSync, see https://github.com/etcd-io/etcd/blob/b9b75f81e56241b0f573ba31b3c3a018290e9343/raft/node.go#L584

Do you know why? @BusyJay

**Comment by BusyJay** [comment]
I have no idea. :crying_cat_face:

**Comment by Tom-Xie** [comment]
test

**Comment by accelsao** [comment]
can someone specify which test cases need to be ported from etcd? or just modify the `mustsync` logic?

**Comment by BusyJay** [comment]
I think all the tests are ported. The issue is related to node, which is not available from raft-rs. We just implement `raw_node`.

@siddontang I believe it's because we don't sync all entries. We just sync those entries that are important like conf change or split. Although, it may not be good as a standalone library. Giving that we have been optimizing the performance of file syncing, I think it's OK to just sync all entries.

@accelsao I think you can modify `mustsync` logic and add a unit test.
